---
name: Missing package
description: Let us know about a package that's missing from piwheels
title: "Missing package: "
labels: [missing package]
body:
  - type: input
    id: package
    attributes:
      label: Package name
      description: The name of the package
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      description: The version(s) of the package which are missing
      placeholder: 1.0, 1.1 or all
    validations:
      required: true
  - type: input
    id: pypi_url
    attributes:
      label: PyPI URL
      description: Link to the PyPI page
      placeholder: https://pypi.org/project/example
    validations:
      required: true
  - type: input
    id: piwheels_url
    attributes:
      label: piwheels URL
      description: Link to the piwheels project page
      placeholder: https://www.piwheels.org/project/example
    validations:
      required: true
  - type: checkbox
    id: python_version
    attributes:
      label: Python version
      description: Which versions of Python are the package missing for?
      options:
        - label: Python 3.9
        - label: Python 3.11
    validations:
      required: true
  - type: dropdown
    id: aware
    attributes:
      label: This is for Raspberry Pi users only
      description: If your issue does not relate to usage on Raspberry Pi using the official distro, please don't create an issue here
      options:
        - "I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi"
    validations:
      required: true
  - type: dropdown
    id: duplicates
    attributes:
      label: Check for duplicate issues
      description: The project page includes links to existing issues about the package. Please check this issue doesn't already exist.
      options:
        - "I have checked for duplicate issues"
    validations:
      required: true
  - type: dropdown
    id: maintainer
    attributes:
      label: Are you the project maintainer?
      description: If you are the maintainer of this package, please let us know
      options:
        - "I am the maintainer"
        - "I am not the maintainer"
  - type: textarea
    id: more-info
    attributes:
      label: More information
      description: Please give more information

---
