---
name: Package issue
description: DO NOT USE. Please use the project page link below.
title: "Package issue: "
labels: [package issue]
body:
  - type: input
    id: package
    attributes:
      label: Package name
      description: The name of the package
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      description: The version(s) of the package to which the issue relates
      placeholder: 1.0, 1.1 or all
    validations:
      required: true
  - type: input
    id: pypi_url
    attributes:
      label: PyPI URL
      description: This has been pre-filled automatically. **Do not change this value.**
      placeholder: https://pypi.org/project/example
    validations:
      required: true
  - type: input
    id: piwheels_url
    attributes:
      label: piwheels URL
      description: This has been pre-filled automatically. **Do not change this value.**
      placeholder: https://www.piwheels.org/project/example
    validations:
      required: true
  - type: checkboxes
    id: python_version
    attributes:
      label: Python version
      description: Which versions of Python do the package issue relate to?
      options:
        - label: Python 3.9
        - label: Python 3.11
    validations:
      required: true
  - type: input
    id: aware
    attributes:
      label: This is for Raspberry Pi users only. If your issue does not relate to usage on Raspberry Pi using the official distro, please don't create an issue here.
      description: Type `yes` to confirm you understand this is the issue tracker specifically for Raspberry Pi
    validations:
      required: true
  - type: input
    id: duplicates
    attributes:
      label: The project page includes links to existing issues about the package. Please check this issue doesn't already exist.
      description: Type `yes` to confirm you have checked for duplicate issues
    validations:
      required: true
  - type: checkboxes
    id: maintainer
    attributes:
      label: Are you the project maintainer?
      description: If you are the maintainer of this package, please let us know
      options:
        - label: "I am the maintainer"
  - type: textarea
    id: more-info
    attributes:
      label: More information
      description: Please give more information

---
