---
name: Package issue
description:  Let us know about an issue that's related to a particular package in piwheels
title: "Package issue: "
labels: [package issue]
body:
  - type: input
    id: package
    attributes:
      label: Package name
      description: The name of the package
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      description: The version(s) of the package to which the issue relates
      placeholder: 1.0, 1.1 or all
    validations:
      required: true
  - type: input
    id: pypi_url
    attributes:
      label: PyPI URL
      description: Link to the PyPI page
      placeholder: https://pypi.org/project/example
    validations:
      required: true
  - type: input
    id: piwheels_url
    attributes:
      label: piwheels URL
      description: Link to the piwheels project page
      placeholder: https://www.piwheels.org/project/example
    validations:
      required: true
  - type: checkboxes
    id: python_version
    attributes:
      label: Python version
      description: To which versions of Python do the package issue relate?
      options:
        - label: Python 3.7
        - label: Python 3.9
        - label: Python 3.11
  - type: checkboxes
    id: maintainer
    attributes:
      label: I am the maintainer
      description: Are you the maintainer of this package?
      options:
        - label: "Yes"
  - type: textarea
    id: more-info
    attributes:
      label: More information
      description: Please give more information

---
